/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/workspace-sync-contract/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=WorkspaceSyncBindings functions/workspaceSyncBindings.d.ts` (hash: 32c91e31b02719ef7c2eeb010b8c4774)
interface __BaseEnv_WorkspaceSyncBindings {
	WORKSPACE_SYNC_BUCKET: R2Bucket;
	WORKSPACE_SYNC_START_ENABLED: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_WorkspaceSyncBindings {}
}
interface WorkspaceSyncBindings extends __BaseEnv_WorkspaceSyncBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORKSPACE_SYNC_START_ENABLED">> {}
}
