import 'fake-indexeddb/auto'
import { IDBFactory } from 'fake-indexeddb'
import { openDB } from 'idb'
import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ wipeFiles: vi.fn(), purgeMail: vi.fn(), fetch: vi.fn() }))
vi.mock('../../services/apiBase', () => ({ apiUrl: (path: string) => path }))
vi.mock('../../services/googleAuth', () => ({ getValidAccessToken: async () => 'google-test' }))
vi.mock('../../services/emailTrialClient', () => ({ getTrialToken: () => 'email-test' }))
vi.mock('../../services/secureFileStorage', () => ({ wipeFileStorage: mocks.wipeFiles }))
vi.mock('../../services/mailAccounts', () => ({ purgeMailAccountsForUser: mocks.purgeMail }))
let store: typeof import('../../services/projects/store')
let users: typeof import('../../services/userSession')
let account: typeof import('../../services/accountService')
let c: typeof import('../../services/crypto')
const session = (userId = 'a') => ({ userId, authMethod: 'email' as const, displayName: userId, email: `${userId}@example.test`, createdAt: 1 })
const deferred = () => { let resolve!: () => void; const promise = new Promise<void>(r => { resolve = r }); return { promise, resolve } }
beforeEach(async () => {
  vi.restoreAllMocks(); vi.resetModules(); localStorage.clear(); globalThis.indexedDB = new IDBFactory()
  mocks.wipeFiles.mockReset().mockResolvedValue(undefined); mocks.purgeMail.mockReset().mockResolvedValue(undefined)
  mocks.fetch.mockReset().mockResolvedValue(new Response('{}', { status: 200 })); vi.stubGlobal('fetch', mocks.fetch)
  users = await import('../../services/userSession'); users.setActiveSession(session())
  c = await import('../../services/crypto'); await c.initCrypto('test')
  store = await import('../../services/projects/store'); account = await import('../../services/accountService')
})
describe('account erasure — durable project integration', () => {
  it('email server success survives a failed local purge and reload, without a second POST', async () => {
    const op = await store.beginProjectOperation(); await store.createProject(op, 'Private project')
    mocks.wipeFiles.mockRejectedValueOnce(new Error('disk busy'))
    await expect(account.deleteAccount()).rejects.toThrow('disk busy')
    const database = await openDB('arty-projects', 1)
    expect(await database.get('meta', ['erasing', 'a'])).toMatchObject({ owner: 'a', serverConfirmed: true })
    expect(users.getActiveUserId()).toBe('a')
    expect(await database.count('projects')).toBe(0)
    vi.resetModules() // fresh JS session, same browser IDB + localStorage
    users = await import('../../services/userSession'); account = await import('../../services/accountService')
    await account.deleteAccount()
    expect(mocks.fetch).toHaveBeenCalledTimes(1)
    expect(users.getActiveUserId()).toBeNull()
    expect(await database.get('meta', ['erasing', 'a'])).toBeUndefined()
    expect(await database.get('usage', 'a')).toBeUndefined()
  })
  it('server failure does not erase any project or turn the fence', async () => {
    const op = await store.beginProjectOperation(), project = await store.createProject(op, 'Keep')
    mocks.fetch.mockResolvedValueOnce(new Response('{}', { status: 401 }))
    await expect(account.deleteAccount()).rejects.toThrow('(401)')
    const fresh = await store.beginProjectOperation()
    expect((await store.getProject(fresh, project.id))?.project?.name).toBe('Keep')
    expect(localStorage.getItem(users.PROJECT_ERASURE_FENCE_KEY)).toBeNull()
    expect(mocks.wipeFiles).not.toHaveBeenCalled()
    expect(await (await openDB('arty-projects', 1)).get('meta', ['erasing', 'a'])).toBeUndefined()
  })
  it('same-window session replacement cancels cleanup and cannot create projects while erasure waits', async () => {
    const gate = deferred()
    mocks.purgeMail.mockReturnValueOnce(gate.promise)
    const pending = account.deleteAccount().catch(error => error)
    await vi.waitFor(() => expect(mocks.purgeMail).toHaveBeenCalled())
    users.setActiveSession(session()); await c.initCrypto('test')
    await expect(store.beginProjectOperation()).rejects.toMatchObject({ code: 'unavailable' })
    gate.resolve()
    expect(await pending).toBeInstanceOf(Error) // changed epoch; no false success
    expect(await (await openDB('arty-projects', 1)).count('projects')).toBe(0)
  })
  it('an independent module/session instance sharing IDB cannot import during or after another instance erases A', async () => {
    const gate = deferred(), originalAccount = account
    mocks.purgeMail.mockReturnValueOnce(gate.promise)
    const pending = originalAccount.deleteAccount()
    await vi.waitFor(() => expect(mocks.purgeMail).toHaveBeenCalled())
    // Two separate module graphs emulate two JS windows, not a real browser
    // E2E. They share only the same fake IDB factory and browser localStorage.
    vi.resetModules()
    const secondUsers = await import('../../services/userSession')
    secondUsers.setActiveSession(session())
    const secondCrypto = await import('../../services/crypto'); await secondCrypto.initCrypto('test')
    const secondStore = await import('../../services/projects/store')
    await expect(secondStore.beginProjectOperation()).rejects.toMatchObject({ code: 'unavailable' })
    gate.resolve(); await pending
    await expect(secondStore.beginProjectOperation()).rejects.toMatchObject({ code: 'cancelled' })
    expect(await (await openDB('arty-projects', 1)).count('projects')).toBe(0)
  })
  it('two successful concurrent owner purges leave the two global fences equal', async () => {
    await store.beginProjectOperation()
    users.removeKnownSession('a')
    await Promise.all([store.purgeProjectsForAccount('a', () => {}), store.purgeProjectsForAccount('b', () => {})])
    const database = await openDB('arty-projects', 1)
    expect(await database.get('meta', 'erasure-fence')).toBe(localStorage.getItem(users.PROJECT_ERASURE_FENCE_KEY))
  })
  it('a confirmed interrupted erasure can repair a fence mismatch on explicit retry', async () => {
    const lease = await store.beginProjectErasure('a', () => {})
    await store.confirmServerProjectErasure(lease)
    localStorage.setItem(users.PROJECT_ERASURE_FENCE_KEY, 'interrupted-fence')
    await expect(store.beginProjectOperation()).rejects.toMatchObject({ code: 'cancelled' })
    await account.deleteAccount()
    expect(mocks.fetch).not.toHaveBeenCalled()
    const database = await openDB('arty-projects', 1)
    expect(await database.get('meta', 'erasure-fence')).toBe(localStorage.getItem(users.PROJECT_ERASURE_FENCE_KEY))
    expect(await database.get('meta', ['erasing', 'a'])).toBeUndefined()
  })
  it.each(['success-first', 'failure-first'])('concurrent server outcomes retain the authenticated success: %s', async order => {
    const first = await store.beginProjectErasure('a', () => {}), second = await store.beginProjectErasure('a', () => {})
    expect(second.operationId).toBe(first.operationId)
    if (order === 'failure-first') await store.releaseFailedProjectErasure(second)
    await store.confirmServerProjectErasure(first)
    if (order === 'success-first') await store.releaseFailedProjectErasure(second)
    const retry = await store.beginProjectErasure('a', () => {})
    expect(retry.serverConfirmed).toBe(true)
    await account.deleteAccount()
    expect(mocks.fetch).not.toHaveBeenCalled()
    expect(users.getActiveUserId()).toBeNull()
  })
  it('cleans an erasure nonce when its guard fails after commit before caller receives it', async () => {
    let checks = 0
    await expect(store.beginProjectErasure('a', () => { if (++checks === 4) throw new Error('changed') })).rejects.toThrow('changed')
    const database = await openDB('arty-projects', 1)
    expect(await database.get('meta', ['erasing', 'a'])).toBeUndefined()
    expect(await store.beginProjectOperation()).toBeTruthy()
  })
  it('confirmed local erasure remains resumable past 32 local retries', async () => {
    await store.confirmServerProjectErasure(await store.beginProjectErasure('a', () => {}))
    for (let i = 0; i < 40; i++) expect((await store.beginProjectErasure('a', () => {})).serverConfirmed).toBe(true)
    await account.deleteAccount()
    expect(mocks.fetch).not.toHaveBeenCalled()
    expect(users.getActiveUserId()).toBeNull()
  })
  it('explicit device-only recovery remains possible at the pending-server-attempt bound', async () => {
    for (let i = 0; i < 32; i++) await store.beginProjectErasure('a', () => {})
    await expect(store.beginProjectErasure('a', () => {})).rejects.toMatchObject({ code: 'unavailable' })
    await account.wipeLocalAccount()
    expect(mocks.fetch).not.toHaveBeenCalled()
    expect(users.getActiveUserId()).toBeNull()
    expect(await (await openDB('arty-projects', 1)).get('meta', ['erasing', 'a'])).toBeUndefined()
  })
})
