// Shared mock data + i18n strings for Arty prototype

const COPY = {
  fr: {
    appName: 'Arty',
    tagline: 'Ton assistant personnel',
    login: {
      title: 'Bon retour',
      subtitle: 'Ton assistant, chiffré, à toi.',
      apikey: 'Clé API',
      google: 'Google',
      email: 'Email',
      continueGoogle: 'Continuer avec Google',
      apiKeyLabel: 'Clé Anthropic',
      apiKeyPlaceholder: 'sk-ant-api03-…',
      start: 'Commencer',
      privacyNote: 'Chiffré localement. Rien ne quitte ton appareil sans toi.',
      recentAccounts: 'Comptes récents',
    },
    home: {
      greetingMorning: 'Bonjour',
      greetingAfternoon: 'Bon après-midi',
      greetingEvening: 'Bonsoir',
      askAnything: 'De quoi as-tu besoin ?',
      placeholder: 'Discuter avec Arty…',
      brief: 'Brief du matin',
      today: "Aujourd'hui",
      suggestions: 'Suggestions',
      sug1: 'Résume mes mails non lus',
      sug2: "Qu'ai-je de prévu aujourd'hui ?",
      sug3: 'Planifie un RDV demain 14h',
      sug4: 'Donne-moi une idée utile',
      connectGoogle: 'Connecter Google',
      connectedAs: 'Connecté',
    },
    chat: {
      title: 'Conversation',
      placeholder: 'Répondre à Arty…',
      typing: 'Arty écrit…',
      emailAction: 'Lecture des mails',
      driveAction: 'Accès à Drive',
      browserAction: 'Navigation web',
      pin: 'Épingler',
      branch: 'Dériver',
      edit: 'Éditer',
    },
    sidebar: {
      new: 'Nouvelle conversation',
      newEU: 'Conversation EU',
      search: 'Rechercher…',
      pinned: 'Épinglés',
      history: 'Historique',
      tasks: 'Tâches',
      settings: 'Paramètres',
      logout: 'Déconnexion',
      import: 'Importer',
      today: "Aujourd'hui",
      yesterday: 'Hier',
      earlier: 'Plus tôt',
    },
    brief: {
      today: "Aujourd'hui",
      agenda: 'Agenda',
      inbox: 'Boîte de réception',
      priorities: 'Priorités',
      weather: 'Valence · 18° nuageux',
      start: 'Commencer la journée',
      unread: 'non lus',
      readAll: 'Résumer tout',
    },
    tasks: {
      title: 'Tâches',
      pending: 'En cours',
      done: 'Terminées',
      empty: 'Rien à faire. Respire.',
      remind: 'Rappeler',
    },
    settings: {
      title: 'Paramètres',
      account: 'Compte',
      keys: 'Clés API',
      google: 'Google',
      memory: 'Mémoire',
      language: 'Langue',
      appearance: 'Apparence',
      theme: 'Direction visuelle',
      notifications: 'Notifications',
      about: 'À propos',
    },
    report: {
      chapter: 'Chapitre',
      byArty: 'Rédigé par Arty',
      readTime: '4 min de lecture',
      title: 'Point fournisseurs — Avril',
      kicker: 'Marché des façades',
      summary: 'Synthèse',
    },
  },
  en: {
    appName: 'Arty',
    tagline: 'Your personal assistant',
    login: {
      title: 'Welcome back',
      subtitle: 'Your assistant, encrypted, yours.',
      apikey: 'API key',
      google: 'Google',
      email: 'Email',
      continueGoogle: 'Continue with Google',
      apiKeyLabel: 'Anthropic key',
      apiKeyPlaceholder: 'sk-ant-api03-…',
      start: 'Start',
      privacyNote: 'Encrypted locally. Nothing leaves your device without you.',
      recentAccounts: 'Recent accounts',
    },
    home: {
      greetingMorning: 'Good morning',
      greetingAfternoon: 'Good afternoon',
      greetingEvening: 'Good evening',
      askAnything: 'What do you need?',
      placeholder: 'Chat with Arty…',
      brief: 'Morning brief',
      today: 'Today',
      suggestions: 'Suggestions',
      sug1: 'Summarise unread mail',
      sug2: "What's on today?",
      sug3: 'Book a meeting tomorrow 2pm',
      sug4: 'Give me a useful idea',
      connectGoogle: 'Connect Google',
      connectedAs: 'Connected',
    },
    chat: {
      title: 'Conversation',
      placeholder: 'Reply to Arty…',
      typing: 'Arty is writing…',
      emailAction: 'Reading mail',
      driveAction: 'Accessing Drive',
      browserAction: 'Browsing web',
      pin: 'Pin',
      branch: 'Branch',
      edit: 'Edit',
    },
    sidebar: {
      new: 'New conversation',
      newEU: 'EU conversation',
      search: 'Search…',
      pinned: 'Pinned',
      history: 'History',
      tasks: 'Tasks',
      settings: 'Settings',
      logout: 'Sign out',
      import: 'Import',
      today: 'Today',
      yesterday: 'Yesterday',
      earlier: 'Earlier',
    },
    brief: {
      today: 'Today',
      agenda: 'Schedule',
      inbox: 'Inbox',
      priorities: 'Priorities',
      weather: 'Valence · 18° cloudy',
      start: 'Start the day',
      unread: 'unread',
      readAll: 'Summarise all',
    },
    tasks: {
      title: 'Tasks',
      pending: 'In progress',
      done: 'Done',
      empty: 'Nothing to do. Breathe.',
      remind: 'Remind me',
    },
    settings: {
      title: 'Settings',
      account: 'Account',
      keys: 'API keys',
      google: 'Google',
      memory: 'Memory',
      language: 'Language',
      appearance: 'Appearance',
      theme: 'Visual direction',
      notifications: 'Notifications',
      about: 'About',
    },
    report: {
      chapter: 'Chapter',
      byArty: 'Written by Arty',
      readTime: '4 min read',
      title: 'Supplier pulse — April',
      kicker: 'Façade market',
      summary: 'Summary',
    },
  },
};

// Shared mock state
const MOCK = {
  user: { name: 'Florent', email: 'florent@facadespollet.fr' },
  conversations: [
    { id: 'c1', title: 'Devis ravalement rue du Parc', when: 'now', group: 'today', preview: "J'ai rédigé le devis, tu veux que je l'envoie ?" },
    { id: 'c2', title: 'Résumé des mails de la semaine', when: '2h', group: 'today', preview: '5 mails importants sur 47.' },
    { id: 'c3', title: 'Recherche prix Point P', when: '5h', group: 'today', preview: 'Parpaing 20cm : 1,89€ · isolant 40mm : 14,30€/m²' },
    { id: 'c4', title: 'Planning chantiers mai', when: 'hier', group: 'yesterday', preview: 'Répartition sur 4 semaines finalisée.' },
    { id: 'c5', title: 'Facturation trimestre', when: 'hier', group: 'yesterday', preview: 'Relance 3 clients en retard.' },
    { id: 'c6', title: 'Projet site vitrine', when: '3j', group: 'earlier', preview: 'Maquette publiée sur WordPress.' },
    { id: 'c7', title: 'Formation équipe sécurité', when: '5j', group: 'earlier', preview: 'Dates validées pour septembre.' },
  ],
  agenda: [
    { time: '09:30', title: 'Visite chantier — Bourg-lès-Valence', dur: '1h30', tag: 'chantier' },
    { time: '11:30', title: 'Appel fournisseur Gedimat', dur: '30 min', tag: 'appel' },
    { time: '14:00', title: 'Devis M. Durand', dur: '1h', tag: 'bureau' },
    { time: '17:00', title: 'Réunion équipe', dur: '45 min', tag: 'équipe' },
  ],
  emails: [
    { from: 'Marie Durand', subject: 'Confirmation RDV jeudi', preview: 'Bonjour Florent, je confirme notre rendez-vous…', unread: true },
    { from: 'Gedimat Valence', subject: 'Nouveau tarif isolation', preview: 'Cher client, nos tarifs pour la saison…', unread: true },
    { from: 'Claire Martin', subject: 'Photos chantier rue du Parc', preview: 'Voici les photos promises…', unread: true },
  ],
  tasks: [
    { id: 't1', title: 'Relancer M. Leclerc pour le devis', due: "Aujourd'hui", done: false },
    { id: 't2', title: "Publier l'article sur le ravalement thermique", due: 'Demain', done: false },
    { id: 't3', title: 'Commander matériel Point P', due: 'Vendredi', done: false },
    { id: 't4', title: 'Envoyer facture client Dupont', due: 'Hier', done: true },
  ],
  chatMessages: [
    { role: 'user', content: 'Résume-moi mes mails non lus importants.' },
    { role: 'action', content: 'chat.emailAction' },
    { role: 'assistant', content: "**3 mails importants aujourd'hui :**\n\n• **Marie Durand** confirme le RDV de jeudi 14h pour le devis.\n\n• **Gedimat** annonce une baisse de 4% sur l'isolation polystyrène à partir du 22.\n\n• **Claire Martin** a envoyé les photos du chantier rue du Parc — elle demande ton retour avant vendredi.", tools: ['gmail'] },
    { role: 'user', content: 'Prépare une réponse à Claire, remercie-la et propose qu\'on se voie sur site lundi matin.' },
    { role: 'assistant', content: "Voici un brouillon :\n\n> Bonjour Claire,\n>\n> Merci pour les photos, elles sont parfaites. Je te propose qu'on se retrouve **lundi matin 9h directement sur le chantier** pour en discuter.\n>\n> À lundi !\n> Florent\n\nTu veux que je l'envoie ?", draft: true },
  ],
};

Object.assign(window, { COPY, MOCK });
